# Generated by Django 4.1.1 on 2022-10-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='disslike',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='like',
        ),
    ]
