# Generated by Django 4.1.1 on 2022-10-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.commentmodel', verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.companymodel', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='platform',
            field=models.ManyToManyField(to='games.platformmodel', verbose_name='platform'),
        ),
    ]
