# Generated by Django 4.1.1 on 2022-10-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='image_body4',
            field=models.ImageField(default=None, upload_to='games/', verbose_name='image body'),
            preserve_default=False,
        ),
    ]
