# Generated by Django 4.1.1 on 2022-11-16 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_likemodel_remove_companymodel_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.ratingmodel'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
