# Generated by Django 4.1.1 on 2022-10-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Star rating',
                'verbose_name_plural': 'Stars rating',
                'ordering': ['-value'],
            },
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='poster',
            field=models.ImageField(default=None, upload_to='games/', verbose_name='poster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='video',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('review', models.TextField(verbose_name='review')),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamemodel', verbose_name='game')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.ratingstar', verbose_name='star')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
