# Generated by Django 4.1.1 on 2022-10-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_ratingstar_remove_gamemodel_image_gamemodel_poster_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='RatingModel',
        ),
        migrations.RenameModel(
            old_name='RatingStar',
            new_name='RatingStarModel',
        ),
        migrations.RenameField(
            model_name='ratingmodel',
            old_name='Game',
            new_name='game',
        ),
    ]
