# Generated by Django 4.1.1 on 2022-10-13 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_rename_rating_ratingmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='comment',
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='poster',
            field=models.ImageField(upload_to='games/poster/', verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='review',
            field=models.TextField(),
        ),
    ]
