# Generated by Django 4.1.1 on 2022-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_gamemodel_comment_ratingmodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='disslike',
            field=models.PositiveIntegerField(default=0, verbose_name='disslike'),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='likes'),
        ),
    ]
