# Generated by Django 4.1.1 on 2022-11-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_ratingmodel_dislike_remove_ratingmodel_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='average_rating',
        ),
    ]
