# Generated by Django 4.1.1 on 2022-11-16 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_alter_ratingmodel_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Average rating'),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='games.gamemodel'),
            preserve_default=False,
        ),
    ]
