# Generated by Django 4.1.1 on 2022-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_ratingmodel_game_alter_ratingmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
