# Generated by Django 4.1.1 on 2022-11-16 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0010_alter_ratingmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='dislike',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='like',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='rating',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
