# Generated by Django 4.1.1 on 2022-11-16 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0011_alter_ratingmodel_dislike_alter_ratingmodel_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
