# Generated by Django 4.1.1 on 2022-11-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_ratingmodel_dislike_alter_ratingmodel_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='average_rating',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Average rating'),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
